export default Em.Controller.extend({
  remoteContent: function() {
    var data = Em.A([]);
    Em.$.ajax({
      url: 'https://api.github.com/search/repositories?q=ember',
    }).then(function(response) {
      data.addObjects(response.items);
    }, function() {
      Em.debug('Error in ember query response');
    });
  return data;
  }.property(),
  staticContent: function() {
    return Em.A(['Afghanistan',
                 '\u00c5land Islands',
                 'Albania',
                 'Algeria',
                 'American Samoa',
                 'Andorra',
                 'Angola',
                 'Anguilla',
                 'Antarctica',
                 'Antigua and Barbuda',
                 'Argentina',
                 'Armenia',
                 'Aruba',
                 'Ascension Island',
                 'Australia',
                 'Austria',
                 'Azerbaijan',
                 'Bahamas',
                 'Bahrain',
                 'Bangladesh',
                 'Barbados',
                 'Belarus',
                 'Belgium',
                 'Belize',
                 'Benin',
                 'Bermuda',
                 'Bhutan',
                 'Bolivia',
                 'Bonaire',
                 'Bosnia and Herzegovina',
                 'Botswana',
                 'Bouvet Island',
                 'Brazil',
                 'British Indian Ocean Territory',
                 'British Virgin Islands',
                 'Brunei',
                 'Bulgaria',
                 'Burkina Faso',
                 'Burundi',
                 'Cambodia',
                 'Cameroon',
                 'Canada',
                 'Cape Verde',
                 'Cayman Islands',
                 'Central African Republic',
                 'Chad',
                 'Chile',
                 'China',
                 'Christmas Island',
                 'Cocos (Keeling) Islands',
                 'Colombia',
                 'Comoros',
                 'Republic of the Congo',
                 'Democratic Republic of the Congo',
                 'Cook Islands',
                 'Costa Rica',
                 'Croatia',
                 'Cuba',
                 'Cura\u00e7ao',
                 'Cyprus',
                 'Czech Republic',
                 'Denmark',
                 'Djibouti',
                 'Dominica',
                 'Dominican Republic',
                 'Ecuador',
                 'Egypt',
                 'El Salvador',
                 'Equatorial Guinea',
                 'Eritrea',
                 'Estonia',
                 'Ethiopia',
                 'Falkland Islands',
                 'Faroe Islands',
                 'Fiji',
                 'Finland',
                 'France',
                 'French Guiana',
                 'French Polynesia',
                 'French Southern and Antarctic Lands',
                 'Gabon',
                 'Gambia',
                 'Georgia',
                 'Germany',
                 'Ghana',
                 'Gibraltar',
                 'Greece',
                 'Greenland',
                 'Grenada',
                 'Guadeloupe',
                 'Guam',
                 'Guatemala',
                 'Guernsey',
                 'Guinea',
                 'Guinea-Bissau',
                 'Guyana',
                 'Haiti',
                 'Heard Island and McDonald Islands',
                 'Vatican City',
                 'Honduras',
                 'Hong Kong',
                 'Hungary',
                 'Iceland',
                 'India',
                 'Indonesia',
                 'Ivory Coast',
                 'Iran',
                 'Iraq',
                 'Ireland',
                 'Isle of Man',
                 'Israel',
                 'Italy',
                 'Jamaica',
                 'Japan',
                 'Jersey',
                 'Jordan',
                 'Kazakhstan',
                 'Kenya',
                 'Kiribati',
                 'Kuwait',
                 'Kyrgyzstan',
                 'Laos',
                 'Latvia',
                 'Lebanon',
                 'Lesotho',
                 'Liberia',
                 'Libya',
                 'Liechtenstein',
                 'Lithuania',
                 'Luxembourg',
                 'Macau',
                 'Macedonia',
                 'Madagascar',
                 'Malawi',
                 'Malaysia',
                 'Maldives',
                 'Mali',
                 'Malta',
                 'Marshall Islands',
                 'Martinique',
                 'Mauritania',
                 'Mauritius',
                 'Mayotte',
                 'Mexico',
                 'Micronesia',
                 'Moldova',
                 'Monaco',
                 'Mongolia',
                 'Montenegro',
                 'Montserrat',
                 'Morocco',
                 'Mozambique',
                 'Myanmar',
                 'Namibia',
                 'Nauru',
                 'Nepal',
                 'Netherlands',
                 'New Caledonia',
                 'New Zealand',
                 'Nicaragua',
                 'Niger',
                 'Nigeria',
                 'Niue',
                 'Norfolk Island',
                 'North Korea',
                 'Northern Mariana Islands',
                 'Norway',
                 'Oman',
                 'Pakistan',
                 'Palau',
                 'Palestine',
                 'Panama',
                 'Papua New Guinea',
                 'Paraguay',
                 'Peru',
                 'Philippines',
                 'Pitcairn Islands',
                 'Poland',
                 'Portugal',
                 'Puerto Rico',
                 'Qatar',
                 'Republic of Kosovo',
                 'R\u00e9union',
                 'Romania',
                 'Russia',
                 'Rwanda',
                 'Saint Barth\u00e9lemy',
                 'Saint Helena',
                 'Saint Kitts and Nevis',
                 'Saint Lucia',
                 'Saint Martin',
                 'Saint Pierre and Miquelon',
                 'Saint Vincent and the Grenadines',
                 'Samoa',
                 'San Marino',
                 'S\u00e3o Tom\u00e9 and Pr\u00edncipe',
                 'Saudi Arabia',
                 'Senegal',
                 'Serbia',
                 'Seychelles',
                 'Sierra Leone',
                 'Singapore',
                 'Sint Maarten',
                 'Slovakia',
                 'Slovenia',
                 'Solomon Islands',
                 'Somalia',
                 'South Africa',
                 'South Georgia',
                 'South Korea',
                 'South Sudan',
                 'Spain',
                 'Sri Lanka',
                 'Sudan',
                 'Suriname',
                 'Svalbard and Jan Mayen',
                 'Swaziland',
                 'Sweden',
                 'Switzerland',
                 'Syria',
                 'Taiwan',
                 'Tajikistan',
                 'Tanzania',
                 'Thailand',
                 'Timor-Leste',
                 'Togo',
                 'Tokelau',
                 'Tonga',
                 'Trinidad and Tobago',
                 'Tunisia',
                 'Turkey',
                 'Turkmenistan',
                 'Turks and Caicos Islands',
                 'Tuvalu',
                 'Uganda',
                 'Ukraine',
                 'United Arab Emirates',
                 'United Kingdom',
                 'United States',
                 'United States Minor Outlying Islands',
                 'United States Virgin Islands',
                 'Uruguay',
                 'Uzbekistan',
                 'Vanuatu',
                 'Venezuela',
                 'Vietnam',
                 'Wallis and Futuna',
                 'Western Sahara',
                 'Yemen',
                 'Zambia',
                 'Zimbabwe']);
  }.property()
});
